#!/usr/bin/env bash


function print-help {
    echo "help"
}

function main {

    if [[ "$#" -eq 0 ]]; then
        print-help
        return
    fi

    while [ "$#" -gt 0 ]; do
        case "$1" in
            -h|-help|--help)
                print-help
                break
            ;;
            -s|-setup|--setup)
                pipenv install
                docker-compose -f crudie.setup.init.yml up -d
                break
            ;;
            *)
                docker-compose -f crudie.run.deps.yml up -d 
                docker-compose -f crudie.run.test.yml up -d 
                pipenv run python test.py 
                break
            ;;
        esac
    done

}

main $@
