#!/usr/bin/env bash


function print-help {
    echo "help"
}

function main {
    case "$1" in
        -h|-help|--help)
            print-help
        ;;
        -db)
            docker-compose -f crudie.run.deps.yml exec -it postgresdb psql -U crudie 
        ;;
        -n|-new|--new)
            make "$@"
        ;;
        -c|-clean|--clean)
            docker-compose -f crudie.run.deps.yml -f crudie.run.test.yml down
        ;;
        -s|-setup|--setup)
            docker-compose -f crudie.run.deps.yml up -d
            sleep 5
            docker-compose -f crudie.setup.init.yml run --rm postgresdb
            docker-compose -f crudie.run.deps.yml down
        ;;
        *)
            docker-compose -f crudie.run.deps.yml up -d 
            docker-compose -f crudie.run.services.yml up -d 
            docker-compose -f crudie.run.test.yml run --rm test
            docker-compose -f crudie.run.deps.yml -f crudie.run.services.yml down
        ;;
    esac
}


function make {
    [ ! -d "$1" ] && mkdir "$1"
    pushd "$1" || return
    [ ! -f Dockerfile ] && touch Dockerfile
    popd || return
    git add "$1".
}


main "$@"
