services:
  postgresdb:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: crudie
    ports:
      - "5432:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
